apiVersion: apps/v1
kind: Deployment
metadata:
  name: fromharness-app
  labels:
    app: fromharness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fromharness
  template:
    metadata:
      labels:
        app: fromharness
    spec:
      containers:
        - name: fromharness
          image: naturalorder/fromharness:lab
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # Optional: if the app needs to run to completion (like a job)
          # command: ["dotnet", "yourapp.dll"]
---
apiVersion: v1
kind: Service
metadata:
  name: fromharness-service
spec:
  selector:
    app: fromharness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
